sidebarPanel(width = 4,
             tabsetPanel(
               tabPanel("Prevalence",
                        hr(),
                        h3("Set a prevalence prior"),
                        hr(),                  
                        sliderInput(inputId = "PriorMean2", 
                                    label = "Specify your prior belief about the mean: ", 
                                    min=0, max=1, value=0.2,step = 0.01),
                        radioButtons(inputId = "lower.value2", 
                                     label="Is the percentile  the upper limit of the mean?", choices=c("Yes","No"),
                                     selected="Yes",inline = T),
                        sliderInput(inputId = "Percentile2", 
                                    label = " Specify the level of confidence that the true value of the mean is greater or lower than the percentile.value: ",
                                    min=0, max=1, value=0.99,step = 0.005),
                        sliderInput(inputId = "PercentileValue2", label = "Specify the lower limit for the mean/median/mode at the specified level of confidence: ", 
                                    value = 0.5, min=0, max=1,step = 0.005),
                        sliderInput(inputId = "PercentilePsi2", 
                                    label = "Specify the level of confidence that a certain fraction of the units under study has a prevalence less than the percentile.median. ", 
                                    min=0.501, max=0.999, value=0.9,step = 0.005),
                        sliderInput(inputId = "PercentileMedian2", label = "Specify the median value that corresponds to the defined psi.percentile. has to be higher than both themean and the percentile: ", 
                                    value = 0.8, min=0, max=1,step = 0.005),
                        sliderInput(inputId = "Percentile95value2", label = "Specify the value that the percentile.median does not exceed with 95% confidence. has to be higher than the percentile", 
                                    value=0.9, min=0, max=1, step = 0.005),
                        h5("Caution! Press 'set priors' only when all values are set. "),
                        radioButtons(inputId = "lower.value.fix", 
                                     label=paste("In case 1 slider gets stuck, select 'Patch', wait and select 'Fixed' to continue"),choices=c("Fixed","Patch"),
                                     selected="Fixed", inline = T)
               ),
               tabPanel("ZeroP",
                        hr(),
                        h3("Set a zero prevalence probability prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric2_tau0", 
                                    label = paste("Specify your prior belief about the Sensitivity: "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value2_tau0", 
                                     label=paste("Is the percentile the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb2_tau0"),
                        sliderInput(inputId = "Percentile2_tau0", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01)
                        
               ),
               tabPanel("Se",
                        hr(),
                        h3("Set a sensitivity prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric2_SE", 
                                    label = paste("Specify your prior belief about the Sensitivity: "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value2_SE", 
                                     label=paste("Is the percentile the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb2_SE"),
                        sliderInput(inputId = "Percentile2_SE", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01)
               ),
               tabPanel("Sp",
                        hr(),
                        h3("Set a specificity prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric2_SP", 
                                    label = paste("Specify your prior belief about the Specificity: "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value2_SP", 
                                     label=paste("Is the percentile the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb2_SP"),
                        sliderInput(inputId = "Percentile2_SP", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01)
               )
             ),
             div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Reset tPriors"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp3", "Example"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior!"),style=icon("check"))
)