sidebarPanel(width = 4,
             tabPanel("Prevalence",
                      hr(),
                      h3("Set a prevalence prior"),
                      hr(),
                      sliderInput(inputId = "PercentileValue3_1", 
                                  label = paste("What is the most likely 1st percentile value for the",input$ID_MeanMedianMode,"of the",input$ID_TrueApp," (perv1):"), 
                                  min=0, max=1, value=0.3,step = 0.01),
                      sliderInput(inputId = "Percentile3_1", 
                                  label = "Specify which is the percentile (per1) that corresponds to the above 1st percentile value: ",
                                  min=0, max=1, value=0.3,step = 0.01),
                      uiOutput("sliders_qq_fb"),
                      sliderInput(inputId = "Percentile3_2", 
                                  label="Specify which is the percentile (per2) that corresponds to the above 2nd percentile: ",
                                  min=0, max=1, value=0.8,step = 0.01),
                      h4("Caution! Please press 'set priors' only when all values of all parameters are set. "),
                      radioButtons(inputId = "lower.value.fix", 
                                   label=paste("In case 1 slider gets stuck, select 'Patch', wait and select 'Fixed' to continue"),choices=c("Fixed","Patch"),
                                   selected="Fixed", inline = T),
                      div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Soft reset"),style=icon("check")),
                      div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp2", "Help"),style=icon("check")),
                      div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior!"),style=icon("check"))
             )
)