sidebarPanel(width = 4,
             tabsetPanel(
               tabPanel("Prevalence", 
                        hr(),
                        h3("Set a prevalence prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric", 
                                    label = paste("Specify your prior belief about the",input$ID_MeanMedianMode,"",input$ID_TrueApp,": "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value", 
                                     label=paste("Is the percentile  the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb"),
                        sliderInput(inputId = "Percentile1", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01),
                        h5("Caution! Press 'set priors' only when all values are set. "),
                        radioButtons(inputId = "lower.value.fix", 
                                     label=paste("In case 1 slider gets stuck, select 'Patch', wait and select 'Fixed' to continue"),choices=c("Fixed","Patch"),
                                     selected="Fixed", inline = T)
               ),
               tabPanel("ZeroP",
                        hr(),
                        h3("Set a zero prevalence probability prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric_tau0", 
                                    label = paste("Specify your prior belief about the Specificity: "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value_tau0", 
                                     label=paste("Is the percentile  the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb_tau0"),
                        sliderInput(inputId = "Percentile1_tau0", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01)

                        
               ),
               tabPanel("Se",  
                        hr(),
                        h3("Set a sensitivity prior"),
                        hr(),                    
                        sliderInput(inputId = "PriorMetric_SE", 
                                    label = paste("Specify your prior belief about the Sensitivity: "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value_SE", 
                                     label=paste("Is the percentile  the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb_SE"),
                        sliderInput(inputId = "Percentile1_SE", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01)

               ),
               tabPanel("Sp",             
                        hr(),
                        h3("Set a specificity prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric_SP", 
                                    label = paste("Specify your prior belief about the Specificity: "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value_SP", 
                                     label=paste("Is the percentile  the upper limit of the",input$ID_MeanMedianMode,"?"), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb_SP"),
                        sliderInput(inputId = "Percentile1_SP", 
                                    label = paste("Specify the level of confidence that the true value of the",input$ID_MeanMedianMode,"is greater or lower than the percentile.value: "),
                                    min=0, max=1, value=0.95,step = 0.01)
               )
             ),
             div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Reset tPriors"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp1", "Example"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior(s)!"),style=icon("check"))
)