sidebarPanel(width = 4,
             hr(),
             h3("Set a prevalence prior"),
             hr(),
             sliderInput(inputId = "PriorMetric", 
                         label = paste("What is the most likely value for the ",input$ID_MeanMedianMode,"of the",input$ID_TrueApp," (tm): "), 
                         min=0, max=1, value=0.6,step = 0.01),
             radioButtons(inputId = "lower.value", 
                          label=paste("Will you set an upper percentile limit for the",input$ID_MeanMedianMode,"of the",input$ID_TrueApp," (lv)? If No, then a lower limit is specified."),choices=c("Yes","No"),
                          selected="No",inline = T),
             uiOutput("sliders_fb"),
             sliderInput(inputId = "Percentile1", 
                         label = paste("Specify the level of confidence (per) that the true value of the",input$ID_TrueApp,"",input$ID_MeanMedianMode,"is more extreme than the percentile limit: "),
                         min=0.51, max=1, value=0.95,step = 0.01),
             h4("Caution! Please press 'set priors' only when all values of all parameters are set. "),
             radioButtons(inputId = "lower.value.fix", 
                          label=paste("In case 1 slider gets stuck, select 'Patch', wait and select 'Fixed' to continue"),choices=c("Fixed","Patch"),
                          selected="Fixed", inline = T),
             div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Soft reset"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp1", "Help"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior(s)!"),style=icon("check"))
             
)