sidebarPanel(width = 4,
             tabsetPanel(
               tabPanel("Prevalence", 
                        hr(),
                        h4("Prior on prevalence"),
                        hr(),
                        sliderInput(inputId = "PercentileValue3_1", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.001),
                        sliderInput(inputId = "Percentile3_1", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.001),
                        uiOutput("sliders_qq22_fb"),
                        sliderInput(inputId = "Percentile3_2", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.001)
               ),
               tabPanel("ZeroP",
                        hr(),
                        h4("Prior on zero prevalence probability"),
                        hr(),
                        sliderInput(inputId = "PercentileValue3_1_tau0", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.001),
                        sliderInput(inputId = "Percentile3_1_tau0", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.001),
                        uiOutput("sliders_qq22_tau0_fb"),
                        sliderInput(inputId = "Percentile3_2_tau0", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.001)
                        
               ),
               tabPanel("Se",  
                        hr(),
                        h4("Prior on sensitivity"),
                        hr(),
                        sliderInput(inputId = "PercentileValue3_1_SE", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.001),
                        sliderInput(inputId = "Percentile3_1_SE", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.001),
                        uiOutput("sliders_qq22_SE_fb"),
                        sliderInput(inputId = "Percentile3_2_SE", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.001)
               ),
               tabPanel("Sp",  
                        hr(),
                        h4("Prior on specificity"),
                        hr(),            
                        sliderInput(inputId = "PercentileValue3_1_SP", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.001),
                        sliderInput(inputId = "Percentile3_1_SP", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.001),
                        uiOutput("sliders_qq22_SP_fb"),
                        sliderInput(inputId = "Percentile3_2_SP", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.001)
               )
             ),
             div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Reset tPriors"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp2", "Example"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior(s)!"),style=icon("check"))
)
