sidebarPanel(width = 4,
             tabsetPanel(
               tabPanel("Prevalence", 
                        hr(),
                        h3("Set a prevalence prior"),
                        hr(),
                        sliderInput(inputId = "PercentileValue3_1", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.01),
                        sliderInput(inputId = "Percentile3_1", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.01),
                        uiOutput("sliders_qq22_fb"),
                        sliderInput(inputId = "Percentile3_2", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.01),
                        h5("Caution! Press 'set priors' only when all values are set. "),
                        radioButtons(inputId = "lower.value.fix", 
                                     label=paste("In case 1 slider gets stuck, select 'Patch', wait and select 'Fixed' to continue"),choices=c("Fixed","Patch"),
                                     selected="Fixed", inline = T)
               ),
               tabPanel("ZeroP",
                        hr(),
                        h3("Set a non-zero prevalence probability prior"),
                        hr(),
                        sliderInput(inputId = "PercentileValue3_1_tau0", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.01),
                        sliderInput(inputId = "Percentile3_1_tau0", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.01),
                        uiOutput("sliders_qq22_tau0_fb"),
                        sliderInput(inputId = "Percentile3_2_tau0", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.01)
                        
               ),
               tabPanel("Se",  
                        hr(),
                        h3("Set a sensitivity prior"),
                        hr(),
                        sliderInput(inputId = "PercentileValue3_1_SE", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.01),
                        sliderInput(inputId = "Percentile3_1_SE", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.01),
                        uiOutput("sliders_qq22_SE_fb"),
                        sliderInput(inputId = "Percentile3_2_SE", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.01)
               ),
               tabPanel("Sp",  
                        hr(),
                        h3("Set a specificity prior"),
                        hr(),            
                        sliderInput(inputId = "PercentileValue3_1_SP", 
                                    label = "Specify the value for the 1st percentile", 
                                    min=0, max=1, value=0.3,step = 0.01),
                        sliderInput(inputId = "Percentile3_1_SP", 
                                    label = "Specify which is the percentile that corresponds to the above 1st percentile: ",
                                    min=0, max=1, value=0.3,step = 0.01),
                        uiOutput("sliders_qq22_SP_fb"),
                        sliderInput(inputId = "Percentile3_2_SP", 
                                    label="Specify which is the percentile that corresponds to the above 2nd percentile: ",
                                    min=0, max=1, value=0.8,step = 0.01)
               )
             ),
             div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Reset tPriors"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp2", "Example"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior(s)!"),style=icon("check"))
)
