sidebarPanel(width = 4,
             tabsetPanel(
               tabPanel("Prevalence", 
                        hr(),
                        h3("Set a prevalence prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric", 
                                    label = paste("What is the most likely value for the",input$ID_MeanMedianMode,"of the",input$ID_TrueApp," (tm): "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value", 
                                     label=paste("Will you set an upper percentile limit for the",input$ID_MeanMedianMode,"of the",input$ID_TrueApp," (lv)? If No, then a lower limit is specified."), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb"),
                        sliderInput(inputId = "Percentile1", 
                                    label = paste("Specify the level of confidence (per) that the true value of the",input$ID_MeanMedianMode,"is more extreme than the percentile limit: "),
                                    min=0.51, max=1, value=0.95,step = 0.01)
               ),
               tabPanel("ZeroP",
                        hr(),
                        h3("Set a non-zero prevalence probability prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric_tau0", 
                                    label = paste("What is the most likely value for the",input$ID_MeanMedianMode," of the non-zero prevalence (tm): "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value_tau0", 
                                     label=paste("Will you set an upper percentile limit for the",input$ID_MeanMedianMode,"of the non-zero prevalence (lv)? If No, then a lower limit is specified."), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb_tau0"),
                        sliderInput(inputId = "Percentile1_tau0", 
                                    label = paste("Specify the level of confidence (per) that the true value of the non-zero prevalence ",input$ID_MeanMedianMode,"is more extreme than the set percentile limit: "),
                                    min=0.51, max=1, value=0.95,step = 0.01)

                        
               ),
               tabPanel("Se",  
                        hr(),
                        h3("Set a sensitivity prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric_SE", 
                                    label = paste("What is the most likely value for the",input$ID_MeanMedianMode,"of the Sensitivity (tm): "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value_SE", 
                                     label=paste("Will you set an upper percentile limit for the",input$ID_MeanMedianMode," of the Sensitivity (lv)? If No, then a lower limit is specified."), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb_SE"),
                        sliderInput(inputId = "Percentile1_SE", 
                                    label = paste("Specify the level of confidence (per) that the true value of the Sensitivity",input$ID_MeanMedianMode,"is more extreme than the percentile limit: "),
                                    min=0.51, max=1, value=0.95,step = 0.01)
               ),
               tabPanel("Sp",  
                        hr(),
                        h3("Set a specificity prior"),
                        hr(),
                        sliderInput(inputId = "PriorMetric_SP", 
                                    label = paste("What is the most likely value for the",input$ID_MeanMedianMode,"of the Specificity (tm): "), 
                                    min=0, max=1, value=0.6,step = 0.01),
                        radioButtons(inputId = "lower.value_SP", 
                                     label=paste("Will you set an upper percentile limit for the",input$ID_MeanMedianMode,"of the Specificity (lv)? If No, then a lower limit is specified."), choices=c("Yes","No"),
                                     selected="No",inline = T),
                        uiOutput("sliders_fb_SP"),
                        sliderInput(inputId = "Percentile1_SP", 
                                    label = paste("Specify the level of confidence (per) that the true value of the Specificity",input$ID_MeanMedianMode,"is more extreme than the percentile limit: "),
                                    min=0.51, max=1, value=0.95,step = 0.01)
               )
             ),
             h4("Caution! Please press 'set priors' only when all values of all parameters are set. "),
             radioButtons(inputId = "lower.value.fix", 
                          label=paste("In case 1 slider gets stuck, select 'Patch', wait and select 'Fixed' to continue"),choices=c("Fixed","Patch"),
                          selected="Fixed", inline = T),
             div(style="display:inline-block;width:30%;text-align: left;",actionButton("buttonPriorReset", "Soft reset"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: center;",actionButton("buttonPriorHelp1", "Help"),style=icon("check")),
             div(style="display:inline-block;width:30%;text-align: right;",actionButton("buttonPrior", "Set prior(s)!"),style=icon("check"))
)
