sidebarPanel(width = 4,
             tabsetPanel(
               tabPanel("Prevalence",
                        sliderInput(inputId = "PriorMean2", 
                                    label = "Specify your prior belief about the mean: ", 
                                    min=0, max=1, value=0.2,step = 0.001),
                        sliderInput(inputId = "Percentile2", 
                                    label = " Specify the level of confidence that the true value of the mean is greater or lower than the percentile.value: ",
                                    min=0, max=1, value=0.99,step = 0.001),
                        sliderInput(inputId = "PercentileValue2", label = "Specify the lower limit for the mean/median/mode at the specified level of confidence: ", 
                                    value = 0.5, min=0, max=1,step = 0.001),
                        radioButtons(inputId = "lower.value2", 
                                     label="Is the percentile  the upper limit of the mean?", choices=c("TRUE","FALSE"), 
                                     selected="TRUE",inline = T),
                        sliderInput(inputId = "PercentilePsi2", 
                                    label = "Specify the level of confidence that a certain fraction of the units under study has a prevalence less than the percentile.median. ", 
                                    min=0, max=1, value=0.70,step = 0.001),
                        sliderInput(inputId = "PercentileMedian2", label = "Specify the median value that corresponds to the defined psi.percentile. has to be higher than both themean and the percentile: ", 
                                    value = 0.8, min=0, max=1,step = 0.001),
                        sliderInput(inputId = "Percentile95value2", label = "Specify the value that the percentile.median does not exceed with 95% confidence. has to be higher than the percentile", 
                                    value=0.9, min=0, max=1, step = 0.001)
               ),
               tabPanel("Sensitivity",
                        sliderInput(inputId = "PriorMean2_SE", 
                                    label = "Specify your prior belief about the mean: ", 
                                    min=0, max=1, value=0.2,step = 0.001),
                        sliderInput(inputId = "Percentile2_SE", 
                                    label = " Specify the level of confidence that the true value of the mean is greater or lower than the percentile.value: ",
                                    min=0, max=1, value=0.99,step = 0.001),
                        sliderInput(inputId = "PercentileValue2_SE", label = "Specify the lower limit for the mean/median/mode at the specified level of confidence: ", 
                                    value = 0.5, min=0, max=1,step = 0.001),
                        radioButtons(inputId = "lower.value2_SE", 
                                     label="Is the percentile  the upper limit of the mean?", choices=c("TRUE","FALSE"), 
                                     selected="TRUE",inline = T),
                        sliderInput(inputId = "PercentilePsi2_SE", 
                                    label = "Specify the level of confidence that a certain fraction of the units under study has a prevalence less than the percentile.median. ", 
                                    min=0, max=1, value=0.70,step = 0.001),
                        sliderInput(inputId = "PercentileMedian2_SE", label = "Specify the median value that corresponds to the defined psi.percentile. has to be higher than both themean and the percentile: ", 
                                    value = 0.8, min=0, max=1,step = 0.001),
                        sliderInput(inputId = "Percentile95value2_SE", label = "Specify the value that the percentile.median does not exceed with 95% confidence. has to be higher than the percentile", 
                                    value=0.9, min=0, max=1, step = 0.001)
               ),
               tabPanel("Specificity",
                        sliderInput(inputId = "PriorMean2_SP", 
                                    label = "Specify your prior belief about the mean: ", 
                                    min=0, max=1, value=0.2,step = 0.001),
                        sliderInput(inputId = "Percentile2_SP", 
                                    label = " Specify the level of confidence that the true value of the mean is greater or lower than the percentile.value: ",
                                    min=0, max=1, value=0.99,step = 0.001),
                        sliderInput(inputId = "PercentileValue2_SP", label = "Specify the lower limit for the mean/median/mode at the specified level of confidence: ", 
                                    value = 0.5, min=0, max=1,step = 0.001),
                        radioButtons(inputId = "lower.value2_SP", 
                                     label="Is the percentile  the upper limit of the mean?", choices=c("TRUE","FALSE"), 
                                     selected="TRUE",inline = T),
                        sliderInput(inputId = "PercentilePsi2_SP", 
                                    label = "Specify the level of confidence that a certain fraction of the units under study has a prevalence less than the percentile.median. ", 
                                    min=0, max=1, value=0.70,step = 0.001),
                        sliderInput(inputId = "PercentileMedian2_SP", label = "Specify the median value that corresponds to the defined psi.percentile. has to be higher than both themean and the percentile: ", 
                                    value = 0.8, min=0, max=1,step = 0.001),
                        sliderInput(inputId = "Percentile95value2_SP", label = "Specify the value that the percentile.median does not exceed with 95% confidence. has to be higher than the percentile", 
                                    value=0.9, min=0, max=1, step = 0.001)
                        
               )
             ),
             div(style="display:inline-block;width:45%;text-align: left;",actionButton("buttonPriorReset", "Reset tPriors"),style=icon("check")),
             div(style="display:inline-block;width:45%;text-align: right;",actionButton("buttonPrior", "Set prior!"),style=icon("check"))
)